### ISSUE TITLE
java.lang.ClassNotFoundException: app.controllers.ActivewebExampleController

### ISSUE THREAD

**Issue by Javix** [javalite/activeweb-simple#5]
I tried to start the `activeweb-simple` application and got the following error:
```
Request URL: http://localhost:8080/activeweb-example/
ContextPath: 
Query String: null
URI Full Path: /activeweb-example/
URI Path: /activeweb-example/
Method: GET
org.javalite.activeweb.ClassLoadException: java.lang.ClassNotFoundException: app.controllers.ActivewebExampleController
```
Why is that ? Thank you.

Used with the below versions:
```
OS X 10.12.4
Java version: 1.8.0_112, vendor: Oracle Corporation
<activejdbc.version>1.4.11</activejdbc.version>
<activeweb.version>1.13</activeweb.version>
```

The only changes I made were:
- use postgresql driver and replace mysql in  `pom.xml`:
```
<dependency>
                        <groupId>org.postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <version>42.1.4</version>
                    </dependency>
```

- modify `database.properties`:
```
development.driver=org.postgresql.Driver
development.url=jdbc:postgresql://localhost/simple_development
development.username=Serguei

test.driver=org.postgresql.Driver
test.url=jdbc:postgresql://localhost/simple_test
test.username=Serguei
```

Then started jetty: `mvn jetty:run`.
Navigated to `http://localhost:8080/activeweb-example/`.

The screenshot is [here](https://drive.google.com/open?id=0B9xwV2TklOdaLUxaMzcwQ2lISHM)

**Comment by ipolevoy** [comment]
@Javix, sorry the README has a problem, fixed now. Navigate to http://localhost:8080.

**Comment by Javix** [comment]
@ipolevoy Yep, thank you ! After grabbing the latest 3 commits it works. The first step is passed - the default route page is displayed. But when clicking on `Books CRUD Example` link, it crashed:
```
Request URL: http://localhost:8080/books
ContextPath: 
Query String: null
URI Full Path: /books
URI Path: /books
Method: GET

org.javalite.activeweb.InitException: There are no connection specs in 'development' environment
	at org.javalite.activeweb.controller_filters.DBConnectionFilter.before(DBConnectionFilter.java:80)
	at org.javalite.activeweb.ControllerRunner.filterBefore(ControllerRunner.java:249)
	at org.javalite.activeweb.ControllerRunner.run(ControllerRunner.java:54)
	at org.javalite.activeweb.RequestDispatcher.doFilter(RequestDispatcher.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1613)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
```
What is wrong with that ?

**Comment by ipolevoy** [comment]
ensure you have the "development" properties set for the DB: https://github.com/javalite/activeweb-simple/blob/master/src/main/resources/database.properties

**Comment by ipolevoy** [comment]
Please, see more here: http://javalite.io/database_configuration

**Comment by Javix** [comment]
@ipolevoy Thank you. Here is what `database.properties` has:
```
development.driver=org.postgresql.Driver
development.url=jdbc:postgresql://localhost/simple_development
development.username=serge-mac

test.driver=org.postgresql.Driver
test.url=jdbc:postgresql://localhost/simple_test
test.username=serge-mac
```

**Comment by ipolevoy** [comment]
The migrator uses different code base, so this is possible. What about the password?

**Comment by Javix** [comment]
I don't have it set in local Des, the same way for all the Rails apps using Postgres (for Rails app I don't event set a user name, it seems like it picks the current user by default). So no clues.

**Comment by Javix** [comment]
Fixed it: I had to put an empty pwd as follows:
```
development.password=
```
Thank you for your help.
