### ISSUE TITLE
Error when editing a Book with Postgresql

### ISSUE THREAD

**Issue by Javix** [javalite/activeweb-simple#6]
When I try to edit an existing book, I get a weird exception:
```
equest URL: http://localhost:8080/books/show/1
ContextPath: 
Query String: null
URI Full Path: /books/show/1
URI Path: /books/show/1
Method: GET

org.javalite.activejdbc.DBException: org.postgresql.util.PSQLException: ERROR: operator does not exist: integer = character varying
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 30, query: SELECT * FROM books WHERE id = ? LIMIT 1, params: 1
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at org.javalite.activejdbc.DB.find(DB.java:471)
	at org.javalite.activejdbc.LazyList.hydrate(LazyList.java:329)
	at org.javalite.activejdbc.AbstractLazyList.isEmpty(AbstractLazyList.java:42)
	at org.javalite.activejdbc.ModelDelegate.findById(ModelDelegate.java:197)
	at app.models.Book.findById(Book.java:2195)
	at app.controllers.BooksController.show(BooksController.java:35)
```
I had to modify the existing migration for Postgresql:
```
CREATE TABLE books (
  id  SERIAL PRIMARY KEY,
  author VARCHAR(128),
  title VARCHAR(128),
  isbn VARCHAR(128),
  created_at timestamp without time zone NOT NULL,
  updated_at timestamp without time zone NOT NULL
);
```

Any idea ? Thank you.

**Comment by ipolevoy** [comment]
must be a PostgreSQL thing. Can you do the same query on command line?

**Comment by Javix** [comment]
I tried from `pgAdmin` SQL editor window ad it worked:
```
select * from books where id=1;
1;"Martin Fowler";"Clean Code";"1234567";"2017-10-25 21:06:42.936";"2017-10-25 21:06:42.937"
```
Weird :(

**Comment by ipolevoy** [comment]
ActiveJDBC uses PreparedStatement, which will dynamically replace a value. 

From your Java code, try: 

    Object o = Base.findAll("SELECT * FROM books WHERE id = ? LIMIT 1", val);

and see what happens.

**Comment by Javix** [comment]
I put it in `BooksControler#show` action just before calling`Book.findById`:
```
public void show(){
        System.out.println("+++++ Object ++++++++++++++++ ");
        //this is to protect from URL hacking
        Object o = Base.findAll("SELECT * FROM books WHERE id = ? LIMIT 1", getId());
        System.out.println("+++++ Object: " + o);
        Book b = (Book) Book.findById(getId());
....
``` 
It looks like the connection has been closed:
```
97688 [qtp641011362-13] INFO org.javalite.activeweb.ControllerRunner - Executing controller: app.controllers.BooksController.show
+++++ Object ++++++++++++++++ 
97693 [qtp641011362-13] INFO org.javalite.activejdbc.DB - Closed connection: org.postgresql.jdbc.PgConnection@61ae7849
97694 [qtp641011362-13] INFO org.javalite.activejdbc.ConnectionsAccess - Detached connection: default from current thread
97694 [qtp641011362-13] ERROR org.javalite.activeweb.RequestDispatcher - ActiveWeb ERROR: 
Request URL: http://localhost:8080/books/show/1
ContextPath: 
Query String: null
URI Full Path: /books/show/1
URI Path: /books/show/1
Method: GET

org.javalite.activejdbc.DBException: org.postgresql.util.PSQLException: ERROR: operator does not exist: integer = character varying
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

**Comment by ipolevoy** [comment]
what JDBC driver are you using? Can you provide the Maven dependency?

**Comment by Javix** [comment]
```
<dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.1.4</version>
        </dependency>
```
I put the same dependency in `db-migrator-maven-plugin` section of the `pom.xml`.

**Comment by ipolevoy** [comment]
found the issue, `BooksController` class:

Change this: 

    Book b = (Book) Book.findById(getId());

to this: 

    Book b = (Book) Book.findById(Convert.toLong(getId()));

The PostgreSQL driver is too dumb to convert a string to a long. MySQL driver is a lot more intuitive

**Comment by ipolevoy** [comment]
Read this page for more information: http://javalite.io/pass_through_framework

**Comment by ipolevoy** [comment]
My code: with PostgreSQL and a much earlier driver (apparently they never fixed it)
https://github.com/javalite/activeweb-simple/tree/workiing_postresql_sample

**Comment by Javix** [comment]
Yeah, thank you, I was almost there trying to convert to Integer: `Integer.valuerOf(getId())`.
Thanks a lot.

**Comment by ipolevoy** [comment]
no, there is a converter for all types: http://javalite.github.io/activejdbc/snapshot/org/javalite/common/Convert.html
and it is more flexible, just look at code. Any time you need to do a small boiler-place code, there is a change JavaLite has a shortcut. Take tome to explore.

**Comment by Javix** [comment]
AH, pretty cool 💭
